# Change these first
owner: SukiCZ # Your GitHub organization or username, where this repository lives
repo: DAO-Upptime # The name of this repository

sites:
  - name: Daolabs Landing page
    url: https://daolabs.com
  - name: Daolabs Community
    url: https://community.daolabs.com
  - name: TON Community
    url: https://toncommunityhub.com
  - name: Autonomys Community
    url: https://community.autonomys.xyz
  - name: Sandbox Community
    url: https://daolabs.socialminingjobs.com

status-website:
  # Add your custom domain name, or remove the `cname` line if you don't have a domain
  # Uncomment the `baseUrl` line if you don't have a custom domain and add your repo name there
  # cname: demo.upptime.js.org
  # baseUrl: /your-repo-name
  baseUrl: /DAO-Upptime
  # logoUrl: https://raw.githubusercontent.com/upptime/upptime.js.org/master/static/img/icon.svg
  logoUrl: https://cdn.prod.website-files.com/640b3cb094c46d79488ecddc/640b3e8c84373f26df5b1f40_dao-labs-logo-svg.svg
  name: DAO Upptime
  introTitle: "DAO Labs offers governance solutions and consulting for blockchain-based businesses"
  introMessage: "DAO Labs' status page monitors the real-time performance and uptime of our governance solutions, consulting services, and blockchain infrastructure tools, ensuring seamless operations for all users."
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO
    - title: Upptime
      href: https://github.com/upptime/upptime

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
